# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sandwich Club
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/_" target="_blank">@_</a>.'
url:                 http://sandwichclub.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Eric Carraway
  url:               https://twitter.com/CarrawayEric
  email:             eric@ericcarraway.com

# Custom vars
version:             1.0.0
